spring:
  application:
    name: cql-translate
  http:
    converters:
      preferred-json-mapper: jackson2
cql:
  ontology-file: ontology/mapping_tree.json
  mappings-file: ontology/mapping_cql.json
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "health, prometheus, info, metric"
server:
  port: 8080
